name: Update Etsy Tags

on:
  workflow_dispatch:

jobs:
  update-tags:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Set OpenAI API key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Set GSHEETS_CREDENTIALS
        run: echo "GSHEETS_CREDENTIALS=${{ secrets.GSHEETS_CREDENTIALS }}" >> $GITHUB_ENV


      - name: Run updateTags
        run: node runUpdate.js
